# workflow 이름 설정
name: Publish to npm

# workflow를 트리거하는 이벤트 설정
on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for OIDC
  contents: write

# 실행할 jobs 설정
jobs:
  publish:
    # Ubuntu 환경에서 실행
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          # Node.js 버전 설정
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build local package
        run: pnpm --filter ./packages/react-toc run build

      - name: Publish to npm
        run: pnpm --filter ./packages/react-toc publish --access public --no-git-checks --provenance
