# workflow 이름 설정
name: Release Please

# workflow를 트리거하는 이벤트 설정
on:
  push:
    branches: ["main"]

permissions:
  contents: write
  issues: write
  pull-requests: write

# 실행할 jobs 설정
jobs:
  release-please:
    # Ubuntu 환경에서 실행
    runs-on: ubuntu-latest

    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
